# Generated by Django 6.0 on 2025-12-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='aadhaar_file',
            field=models.FileField(blank=True, null=True, upload_to='aadhaar_docs/'),
        ),
    ]
